//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC1stApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class age
    {
        public int ageid { get; set; }
        public int memberid { get; set; }
        public int age1 { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual family family { get; set; }
    }
}
