//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int cartid { get; set; }
        public int product_id { get; set; }
        public string customer_id { get; set; }
        public int cartstatusid { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
